services:
  - type: web
    name: fastapi-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    buildCommand: |
      pyenv install 3.10.13
      pyenv global 3.10.13
      pip install -r requirements.txt
    startCommand: uvicorn server.main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
